### PR TITLE
Sleep when we don't receive any data.

### PR DESCRIPTION
**Pull request by stoeffel**

### CODE REVIEW

**Comment by jwoudenberg-nri** [comment]
Do you remember if we had this problem before the streams change? Wondering if we should revert it. I think the experience of seeing the entries as soon as they're logged is kinda nice.

**Comment by jwoudenberg-nri** [comment]
Oh wait, I see, we _had_ a threadDelay in the old setup as well, but it was just 100ms. I had forgotten about that, sorry.

How would you feel about using 100ms as a delay here too?

**Comment by stoeffel** [comment]
Sure!

**Comment by stoeffel** [comment]
done and yes we had the same problem, expect that we had the delay there.

**Pull request merged**
