### PR TITLE
Ghc update 924

### PR DESCRIPTION
**Pull request by caiquefigueiredo**
### TODO
- [ ] Generate bounds for non-nix-users
- [X] Make Travis use ghc 9.2.4 rather than 9.0
- [ ] Possibly keep ghc 8.10.7 around
- [X] Fix kafka tests (only failing for M1 machimes)

### CODE REVIEW

**Comment by stoeffel** [comment]
A have a vague memory that the Kafka tests timed out even before the upgrade. Do you know if it's the test library that timesout? We could make this configurable via a env var https://github.com/NoRedInk/haskell-libraries/blob/f2a5db7e98d657052162429d00d48fef7ffc941b/nri-prelude/src/Test/Internal.hs#L419

**Comment by caiquefigueiredo** [comment]
I've set that to `50_000` and still timed out 😭 
Maybe I could give it even more time, but I think it may be due to a breaking change on `hw-kafka-client`. Still haven't browsed it though.

**Comment by caiquefigueiredo** [comment]
Just noticed, but it's apparently passing for Travis. It might be something specific to my machine or M1's 🤔

**Comment by caiquefigueiredo** [comment]
Kafka logs are showing the following error:
```
[2022-08-25 15:51:09,895] ERROR [ReplicaManager broker=0] Error processing append operation on partition 16d73d39-38e4-4637-b74f-ca95f7ac747a-1 (kafka.server.ReplicaManager)
org.apache.kafka.common.KafkaException: org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=Mac and os.arch=aarch64
```

**Comment by jali-clarke** [comment]
superceded by https://github.com/NoRedInk/haskell-libraries/pull/98

**Pull request closed without merging**
